### ISSUE TITLE
Меню второго уровня на странице проектов

### ISSUE THREAD

**Issue by neoromantic** [gooditworks/goodit-works-website#10]
На странице с подробным описанием проектов появляется меню второго уровня. Далее предполагаем что оно может быть не только на ней, но и на других страницах в будущем.

### Требования

- При скролле фиксируем меню вверху экрана
- Логотип плавно уменьшаем
- При скролле выделяем соответствующие пункты

[Внешний вид меню](https://www.figma.com/file/dHmDu73cURj22KlWvwHOsQY0/%D0%B3%D1%83%D0%B4%D0%B8%D1%82%D0%B2%D0%BE%D1%80%D0%BA%D1%81?node-id=320%3A1724)

- Решения по анимации должны быть чисто CSS
- По мере скролла должен обновляться URL
- Не использовать никаких крупных новых зависимостей

**Comment by ksoiss** [comment]
- добавить скролл и правильное позиционирование по клику на проект
- поправить отступы у главного и меню второго уровня (второй уровень съехал левее, чем надо)
- выравнять меню по другому краю
