### ISSUE TITLE
Измерять и посылать в GA Web Vitals

### ISSUE THREAD

**Issue by neoromantic** [gooditworks/goodit-works-website#48]
Вот статья: https://sergiodxa.com/articles/next/web-vitals/

Вот документация Некста: https://nextjs.org/docs/advanced-features/measuring-performance

Есть вот такая заделка чья-то, но не ясно в какой стадии: https://nextvitals.com 

---

Мы хотим сделать то что написано в доке некста: чтобы репортились значения и посылались в GA.

Задача со звездочкой: как-то прокидывать это в Slack (про прод) и в PR (про превью ветки). Чтобы видеть деградации если они происходят. Тут важнее придумать и описать как мы это хотим, чем сделать.

Всё это делается не для сайта, а для любого нашего будущего Next-приложения, поэтому должно быть стандартизировано.

**Comment by kambala3000** [comment]
> Есть вот такая заделка чья-то, но не ясно в какой стадии: https://nextvitals.com

Написано что работа над сервисом еще идет, можно записаться на будущую бету. Расценки жесткие.

> Вот документация Некста: https://nextjs.org/docs/advanced-features/measuring-performance

Я правильно понял, что эти метрики отправляются в GA для того чтобы посмотреть, как сайт ведет себя у разных юзеров?



> Задача со звездочкой: как-то прокидывать это в Slack (про прод) и в PR (про превью ветки). Чтобы видеть деградации если они происходят. Тут важнее придумать и описать как мы это хотим, чем сделать.

Не относится ли это к проверке деплоев лайтахаусом? Я так понял, что он меряет все, кроме first input delay.

**Comment by neoromantic** [comment]
Это новый API реализованный в хроме для получения метрик загрузки и рендеринга сайта на клиенте. 
 
Эти метрики можно собирать и видеть как реально у юзеров что происходит. 

Лайтхаус это тестирование на твоём компе для того чтобы смотреть на деградации и аудиты. А тут - фактические пользовательские данные. Которые зависят и от устройства и от региона и от соединения и так далее. 

Их можно отправлять в GA, можно куда-то ещё. В GA - просто и полезно. 

Сергей.
