### ISSUE TITLE
Исправить тени под блоками проектов

### ISSUE THREAD

**Issue by neoromantic** [gooditworks/goodit-works-website#9]
- попросить Нелли унифицировать тени
- по умолчанию на проектах тени нет
- при ховере выводится тень 
- добавить в CMS поле "Картинка проекта с тенью"

**Comment by kambala3000** [comment]
- на главной странице у всех кейсов должна быть такая-же (маленькая) тень как у талантов
- экспортнуть картинки с одинаковыми тенями и загрузить в цмс
